pipeline {
    agent any
 
    tools {
        maven 'Maven_3'
    }
 
    stages {
 
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/Harsh-Panghal/java_with_selenium'
            }
        }
 
        stage('Build') {
            steps {
                dir('php_travel_cucumberBDD') {
                    bat 'mvn clean'
                }
            }
        }
 
        stage('Compile') {
            steps {
                dir('php_travel_cucumberBDD') {
                    bat 'mvn compile'
                }
            }
        }
 
        stage('Test') {
            steps {
                dir('php_travel_cucumberBDD') {
                    bat 'mvn test'
                }
            }
        }
 
        stage('Package') {
            steps {
                dir('php_travel_cucumberBDD') {
                    bat 'mvn package'
                }
            }
        }
        stage('Docker Build') {
    		steps {
        		dir('php_travel_cucumberBDD') {
                    bat 'docker build -t cucumber-framework .'
                }
    }
}
 
	stage('Docker Run') {
    		steps {
        		dir('php_travel_cucumberBDD') {
                    bat 'docker run --rm cucumber-framework'
                }
    	}
    }
 
    post {
        success {
            echo 'Build Successful'
        }
 
        failure {
            echo 'Build Failed'
        }
    }
}